
version: 2.1

jobs:
  ios: 
    macos:
      xcode: "11.3.0"
    working_directory: ~/discipline
    environment:
      FL_OUTPUT_DIR: output
    parameters:
      app_env:
        type: string
    steps:
      - checkout

      - restore_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}

      - run: yarn install

      - save_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}
          paths:
            - ~/.cache/yarn

      - restore_cache:
          key: bundle-v1-{{ checksum "ios/Gemfile.lock" }}-{{ arch }}

      - run:
          command: bundle check || bundle install --path ../.bundle
          working_directory: ios

      - save_cache:
          key: bundle-v1-{{ checksum "ios/Gemfile.lock" }}-{{ arch }}
          paths:
            - .bundle

      - restore_cache:
          key: 1-pods-{{ checksum "ios/Podfile.lock" }}

      - run:
          command: bundle exec pod install
          working_directory: ios

      - save_cache:
          key: 1-pods-{{ checksum "ios/Podfile.lock" }}
          paths:
            - ios/Pods

      - run:
          name: Fastlane
          command: bundle exec fastlane ios << parameters.app_env >>
      - store_artifacts:
          path: output

workflows:
  deploy:
    jobs:
      - ios:
          filters:
            branches:
              only: release
          app_env: pro
      - ios:
          filters:
            branches:
              only: master
          app_env: beta
