
version: 2
jobs:
  ios: 
    macos:
      xcode: "11.3.0"
    working_directory: ~/discipline
    environment:
      FL_OUTPUT_DIR: output
    steps:
      - checkout

      - restore_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}

      - run: yarn install

      - save_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}
          paths:
            - ~/.cache/yarn

      - restore_cache:
          key: bundle-v1-{{ checksum "ios/Gemfile.lock" }}-{{ arch }}

      - run:
          command: bundle check || bundle install --path ../.bundle
          working_directory: ios

      - save_cache:
          key: bundle-v1-{{ checksum "ios/Gemfile.lock" }}-{{ arch }}
          paths:
            - .bundle

      - run:
          command: bundle exec pod install
          working_directory: ios

      - run:
          name: Fastlane
          command: bundle exec fastlane ios pro
      - store_artifacts:
          path: output

workflows:
  version: 2
  deploy:
    jobs:
      - ios:
          filters:
            branches:
              only: release


